name: Build Custom Rapid Response image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build Docker Image'
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          registry: ghcr.io
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
          repository: dark-vex/ra-custom
          tags: latest
          push: true
