name: Build Custom Rapid Response image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        id: test-image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          tags: latest

  build_release:
    runs-on: ubuntu-latest
    needs: build_image
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        id: release
        uses: rymndhng/release-on-push-action@master
        with:
          release_name: "Rapid Response custom <RELEASE_TAG>"
          bump_version_scheme: minor

      - name: 'Build Docker Image'
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          registry: ghcr.io
          username: "dark-vex"
          password: ${{ secrets.REPO_SCOPED_TOKEN }}
          repository: dark-vex/ra-custom
          tags: latest, ${{ steps.release.outputs.tag_name }}
          push: true

    outputs:
      version: ${{ steps.release.outputs.version }}
